from .artists import ArtistsPage
from .debug import DebugPage
from .library import LibraryPage
from .playlists import PlaylistsPage
from .stations import StationsPage
from .playerqueue import QueuePage
from .search import SearchPage
from .settings import SettingsPage
from .album import AlbumsPage
